name: Tests

on:
  push:
    branches: [pipeline]
  workflow_dispatch:
    inputs:
        environment:
          type: string
          default: DEV
          required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install --force
    - name: Run unit tests
      run: npm run tests
    
    - name: Install newman
      run: |
        npm install -g newman --force
    - name: Run integration tests
      run: newman run ${{ secrets.COLLECTION_LINK }} -e 
            Test_Dinners.postman_environment.json